### ISSUE TITLE
add a conditional deferred undo to delete the enclave if the test isn't in execution any more

### ISSUE THREAD

**Issue by h4ck3rk3y** [kurtosis-tech/examples#20]
https://github.com/kurtosis-tech/examples/blob/35327699a1eea585ab987d45291a4ae048acc117/ethereum-network-partition-test/main_test.go#L103

**Comment by h4ck3rk3y** [comment]
Paritosh from ethereum reported it earlier today.

**Comment by h4ck3rk3y** [comment]
Perhaps we want to keep it this way as we want the enclave to be there so that the user can look at enclaves if necessary. Or we could make it configurable

**Comment by mieubrisse** [comment]
@h4ck3rk3y this would just be changing https://github.com/kurtosis-tech/examples/blob/35327699a1eea585ab987d45291a4ae048acc117/ethereum-network-partition-test/main_test.go#L114 to `DeleteEnclave`. It was left as `StopEnclave` in case the user wanted to inspect anything that happened during the run (e.g. the logs)
